### ISSUE TITLE
[BUG] Push notification to many profiles

### ISSUE THREAD

**Issue by sahilsarpal15** [mohitmamoria/horntell-node-sdk#2]
The API method breaks if we pass in empty array.

**Comment by mohitmamoria** [comment]
@sahilsarpal15 Thanks for pointing out. Fixing it.

**Comment by sahilsarpal15** [comment]
@mohitmamoria it is not fixed yet!

**Comment by mohitmamoria** [comment]
@sahilsarpal15 Sorry.. fixng it.!
